"use client"

import { useState, useEffect, useRef } from "react"
import { useRouter, useSearchParams } from "next/navigation"
import { Shell } from "@/components/dashboard-v2/shell"
import CampaignBuilderPage from "../builder/page"
import {
  Sparkles, CheckCircle2, Circle, ArrowRight,
  Image as ImageIcon, Search, Rocket, ChevronDown, RefreshCw,
  Download, Copy, Wand2, Check, ExternalLink, Loader2,
} from "lucide-react"
import { cn } from "@/lib/utils"

const CHIPS = [
  { id: "objective", label: "Ad Objective" },
  { id: "audience", label: "Target Audience" },
  { id: "age", label: "Age" },
  { id: "location", label: "Location" },
  { id: "budget", label: "Budget" },
]

const KEYWORD_MAP: Record<string, RegExp> = {
  objective: /sell|promote|generate leads?|drive|awareness|install/i,
  audience: /women|men|audience|people|customers?|target/i,
  age: /\b\d{2}\s*[-–]\s*\d{2}\b|\bage\b|\byears?\b/i,
  location: /india|us|uk|city|cities|tier|country|region|location/i,
  budget: /\$|\b\d+\s*(?:\/day|per day|daily|budget)\b|budget/i,
}

const AD_STYLES = ["Luxury", "Bold", "Minimal", "Festive", "Corporate", "Playful"]
const ASPECT_RATIOS = [
  { label: "1:1", desc: "Square" },
  { label: "4:5", desc: "Portrait" },
  { label: "16:9", desc: "Landscape" },
  { label: "9:16", desc: "Story" },
]
const GOALS = [
  { value: "LEADS", label: "Generate leads" },
  { value: "SALES", label: "Drive sales" },
  { value: "TRAFFIC", label: "Website traffic" },
  { value: "AWARENESS", label: "Brand awareness" },
]
const PLATFORMS = [
  { value: "GOOGLE", label: "Google Ads" },
  { value: "META", label: "Meta Ads" },
]
const META_OBJECTIVES = [
  { value: "AWARENESS", label: "Awareness" },
  { value: "TRAFFIC", label: "Traffic" },
  { value: "ENGAGEMENT", label: "Engagement" },
  { value: "LEADS", label: "Leads" },
  { value: "SALES", label: "Sales" },
  { value: "APP_PROMOTION", label: "App Promotion" },
]
const META_ENABLED = process.env.NEXT_PUBLIC_ENABLE_META_ADS === "true"

const TEMPLATES = [
  { label: "Leads", goal: "LEADS", budget: 1, prompt: "Generate local leads for my service. Focus on people ready to book a consultation this week." },
  { label: "Sales", goal: "SALES", budget: 1, prompt: "Drive sales for my online store. Focus on high-intent shoppers looking for this product now." },
  { label: "Traffic", goal: "TRAFFIC", budget: 1, prompt: "Send qualified traffic to my website. Focus on people researching this category before buying." },
  { label: "Local service", goal: "LEADS", budget: 1, prompt: "Get calls and form leads for my local service business from nearby customers." },
]

type Tab = "campaign" | "boolean" | "creatives" | "launch"

const TABS: { id: Tab; label: string; icon: React.ElementType }[] = [
  { id: "campaign", label: "Campaign", icon: Sparkles },
  { id: "boolean", label: "Boolean search", icon: Search },
  { id: "creatives", label: "AI Creatives", icon: ImageIcon },
  { id: "launch", label: "Launch Ads", icon: Rocket },
]

type CreativeVariation = {
  headline: string
  body?: string
  description?: string
  cta?: string
  score?: number
}

type EnhancedBrief = {
  enhancedText: string
  productOrOffer: string
  targetCustomer: string
  painPoints: string[]
  differentiators: string[]
  proofPoints: string[]
  geography: string
  goal: string
  tone: string
  restrictions: string[]
  missingQuestions: string[]
}

async function readJson(res: Response) {
  try {
    return await res.json()
  } catch {
    return null
  }
}

function CreativeCard({
  variation,
  imageUrl,
  ratio,
}: {
  variation: CreativeVariation
  imageUrl: string | null
  ratio: string
}) {
  const [copied, setCopied] = useState(false)
  const handleCopy = () => {
    navigator.clipboard.writeText([variation.headline, variation.body || variation.description].filter(Boolean).join("\n")).catch(() => {})
    setCopied(true)
    setTimeout(() => setCopied(false), 1500)
  }
  return (
    <div className="sku-card overflow-hidden group">
      <div
        className="w-full relative overflow-hidden bg-[#F0F2F5] flex items-center justify-center"
        style={{
          aspectRatio: ratio === "16:9" ? "16/9" : ratio === "4:5" ? "4/5" : ratio === "9:16" ? "9/16" : "1/1",
          maxHeight: 200,
        }}
      >
        {imageUrl ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img src={imageUrl} alt={variation.headline} className="w-full h-full object-cover" />
        ) : (
          <div className="flex flex-col items-center gap-1.5 p-4 text-center">
            <ImageIcon size={20} className="text-[#D1D5DB]" />
            <p className="text-[10.5px] text-[#9CA3AF]">Image unavailable — copy still generated by AI</p>
          </div>
        )}
        <div className="absolute inset-0 bg-black/0 group-hover:bg-black/25 transition-colors flex items-center justify-center gap-2 opacity-0 group-hover:opacity-100">
          <button onClick={handleCopy} className="w-8 h-8 bg-white rounded-full flex items-center justify-center text-[#374151] shadow hover:bg-[#F0F2F5] transition-colors">
            {copied ? <Check size={14} className="text-[#2E9E5B]" /> : <Copy size={14} />}
          </button>
          {imageUrl && (
            <a href={imageUrl} download target="_blank" rel="noreferrer" className="w-8 h-8 bg-white rounded-full flex items-center justify-center text-[#374151] shadow hover:bg-[#F0F2F5] transition-colors">
              <Download size={14} />
            </a>
          )}
        </div>
      </div>
      <div className="px-3 py-2.5">
        <p className="text-[12px] font-semibold text-[#111827] leading-snug line-clamp-2">{variation.headline}</p>
        <p className="text-[10.5px] text-[#9CA3AF] mt-0.5 line-clamp-2">{variation.body || variation.description}</p>
        {variation.cta && (
          <span className="inline-flex items-center mt-1.5 text-[10px] font-bold text-[#1F57F5] bg-[#EAF0FE] px-2 py-0.5 rounded-full">{variation.cta}</span>
        )}
      </div>
    </div>
  )
}

function inferLocation(text: string) {
  const value = text.toLowerCase()
  if (/\bindia|mumbai|delhi|bangalore|bengaluru|hyderabad|chennai|kolkata|pune\b/.test(value)) return "India"
  if (/\buk|united kingdom|london|england\b/.test(value)) return "United Kingdom"
  if (/\bus|usa|united states|america|new york|california\b/.test(value)) return "United States"
  return ""
}

export default function NewCampaignPage() {
  const [activeTab, setActiveTab] = useState<Tab>("campaign")
  const [prompt, setPrompt] = useState("")
  const [budget, setBudget] = useState(50)
  const [location, setLocation] = useState("")
  const [landingPageUrl, setLandingPageUrl] = useState("")
  const [goal, setGoal] = useState("LEADS")
  const [platform, setPlatform] = useState("GOOGLE")
  const [metaObjective, setMetaObjective] = useState("")
  const [detected, setDetected] = useState<Set<string>>(new Set())
  const [enhancing, setEnhancing] = useState(false)
  const [enhanceError, setEnhanceError] = useState("")
  const [enhancedBrief, setEnhancedBrief] = useState<EnhancedBrief | null>(null)
  const [clarifications, setClarifications] = useState<string[]>([])
  const [building, setBuilding] = useState(false)
  const [built, setBuilt] = useState(false)
  const [campaignPlanId, setCampaignPlanId] = useState<string | null>(null)
  const [campaignName, setCampaignName] = useState("")
  const [buildError, setBuildError] = useState("")

  // Google connection + workspace brand (real context for AI Creatives)
  const [googleConnected, setGoogleConnected] = useState<boolean | null>(() => {
    if (typeof window === "undefined") return null
    const cached = window.sessionStorage.getItem("growzzy_google_connected")
    return cached === null ? null : cached === "true"
  })
  const [metaConnected, setMetaConnected] = useState<boolean | null>(() => {
    if (typeof window === "undefined") return null
    const cached = window.sessionStorage.getItem("growzzy_meta_connected")
    return cached === null ? null : cached === "true"
  })
  const [brand, setBrand] = useState<{ name?: string; industry?: string; toneOfVoice?: string; productDescription?: string } | null>(null)

  // Creatives state
  const [creativesPrompt, setCreativesPrompt] = useState("")
  const [selectedStyle, setSelectedStyle] = useState("Luxury")
  const [selectedRatio, setSelectedRatio] = useState("1:1")
  const [generatingCreatives, setGeneratingCreatives] = useState(false)
  const [creativesError, setCreativesError] = useState("")
  const [generatedCreatives, setGeneratedCreatives] = useState<CreativeVariation[]>([])
  const [generatedImageUrls, setGeneratedImageUrls] = useState<string[]>([])
  const [creativesCount, setCreativesCount] = useState(4)

  // Boolean search
  const [booleanQuery, setBooleanQuery] = useState("")
  const [booleanLoading, setBooleanLoading] = useState(false)
  const [booleanError, setBooleanError] = useState("")
  const [booleanResult, setBooleanResult] = useState<{ interpretation: string; keywords: { text: string; matchType: string; rationale: string }[]; negativeKeywords: string[] } | null>(null)

  // Launch
  const [launching, setLaunching] = useState(false)
  const [launchError, setLaunchError] = useState("")
  const [launched, setLaunched] = useState<{ externalCampaignId?: string } | null>(null)

  const router = useRouter()
  const searchParams = useSearchParams()
  const textareaRef = useRef<HTMLTextAreaElement>(null)
  const editorPlanId = searchParams.get("id") || searchParams.get("plan")

  useEffect(() => {
    const s = new Set<string>()
    for (const [k, r] of Object.entries(KEYWORD_MAP)) {
      if (r.test(prompt)) s.add(k)
    }
    setDetected(s)
  }, [prompt])

  useEffect(() => {
    const reuseId = searchParams.get("reuse")
    if (!reuseId) return
    fetch(`/api/ai/campaign-plan/${reuseId}`, { cache: "no-store" })
      .then((r) => (r.ok ? r.json() : null))
      .then((json) => {
        const brief = json?.data?.briefInput
        if (!brief) return
        if (brief.offer) setPrompt(brief.offer)
        if (brief.budget) setBudget(brief.budget)
        if (brief.location) setLocation(brief.location)
        if (brief.landingPageUrl) setLandingPageUrl(brief.landingPageUrl)
        if (brief.goal) setGoal(brief.goal)
        if (brief.enhancedBrief) {
          setEnhancedBrief(brief.enhancedBrief)
          setClarifications(Array.isArray(brief.clarifications) ? brief.clarifications.map((item: any) => String(item?.answer || "")) : [])
        }
        if (brief.platform === "META" && META_ENABLED) setPlatform("META")
        if (brief.metaObjective) setMetaObjective(brief.metaObjective)
      })
      .catch(() => {})
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    fetch("/api/integrations/status", { cache: "no-store" })
      .then((r) => (r.ok ? r.json() : null))
      .then((json) => {
        const google = !!json?.google?.connected && !!json?.google?.hasAdsAccount
        const meta = !!json?.meta?.connected && !!json?.meta?.hasAdsAccount
        setGoogleConnected(google)
        setMetaConnected(meta)
        window.sessionStorage.setItem("growzzy_google_connected", String(google))
        window.sessionStorage.setItem("growzzy_meta_connected", String(meta))
      })
      .catch(() => {})
    fetch("/api/workspaces", { cache: "no-store" })
      .then((r) => (r.ok ? r.json() : null))
      .then((json) => {
        const w = json?.workspaces?.[0]
        if (w) setBrand({ name: w.name, industry: w.industry, toneOfVoice: w.toneOfVoice, productDescription: w.productDescription })
      })
      .catch(() => {})
  }, [])

  const handleEnhance = async () => {
    if (!prompt.trim() || enhancing) return
    setEnhancing(true)
    setEnhanceError("")
    try {
      const res = await fetch("/api/ai/enhance-prompt", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt: prompt.trim(), budget, location: effectiveLocation || undefined, goal }),
      })
      const json = await readJson(res)
      if (!res.ok || !json?.enhanced || !json?.brief) throw new Error(json?.error?.message || "AI Enhance is temporarily unavailable. Your original brief has not been changed.")
      setPrompt(json.enhanced)
      setEnhancedBrief(json.brief)
      setClarifications((json.brief.missingQuestions || []).map(() => ""))
    } catch (error: any) {
      setEnhanceError(error?.message || "AI Enhance is temporarily unavailable. Your original brief has not been changed.")
    } finally {
      setEnhancing(false)
    }
  }

  const effectiveLocation = location.trim() || inferLocation(prompt)
  const buildLocation = effectiveLocation || "United States"
  const canBuildPlan = !!prompt.trim() && !building && (platform !== "META" || !!metaObjective)

  const handleBuild = async () => {
    if (!canBuildPlan) return
    setBuilding(true)
    setBuildError("")
    try {
      const res = await fetch("/api/ai/campaign-builder", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          offer: prompt.trim(),
          targetCustomer: enhancedBrief?.targetCustomer || prompt.trim().slice(0, 200),
          budget,
          location: buildLocation,
          goal,
          landingPageUrl: landingPageUrl.trim() || undefined,
          enhancedBrief: enhancedBrief || undefined,
          clarifications: enhancedBrief?.missingQuestions.map((question, index) => ({ question, answer: clarifications[index]?.trim() || "" })).filter((item) => item.answer) || undefined,
          platform,
          metaObjective: platform === "META" ? metaObjective : undefined,
        }),
      })
      const json = await readJson(res)
      if (!res.ok || !json?.campaignPlanId) {
        const platformName = platform === "META" ? "Meta Ads" : "Google Ads"
        throw new Error(json?.error?.message || json?.error || `Couldn't build a plan. Connect ${platformName} and select an account first.`)
      }
      setCampaignPlanId(json.campaignPlanId)
      setCampaignName(json.plan?.campaignName || "")
      setBuilt(true)
      window.dispatchEvent(new Event("growzzy:prompt-history-updated"))
      router.replace(`/dashboard/campaigns/new?id=${json.campaignPlanId}`)
    } catch (err: any) {
      setBuildError(err?.message || "Something went wrong building your plan.")
    } finally {
      setBuilding(false)
    }
  }

  const handleBooleanSearch = async () => {
    if (!booleanQuery.trim() || booleanLoading) return
    setBooleanLoading(true)
    setBooleanError("")
    setBooleanResult(null)
    try {
      const res = await fetch("/api/ai/boolean-audience", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ query: booleanQuery.trim() }),
      })
      const json = await readJson(res)
      if (!res.ok || !json?.ok) throw new Error(json?.error || "Couldn't translate this query.")
      setBooleanResult({ interpretation: json.interpretation, keywords: json.keywords, negativeKeywords: json.negativeKeywords })
    } catch (err: any) {
      setBooleanError(err?.message || "Something went wrong searching this audience.")
    } finally {
      setBooleanLoading(false)
    }
  }

  const handleGenerateCreatives = async () => {
    if (generatingCreatives) return
    setGeneratingCreatives(true)
    setCreativesError("")
    setGeneratedCreatives([])
    setGeneratedImageUrls([])
    try {
      const res = await fetch("/api/ai/generate-creatives", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          businessName: brand?.name,
          industry: brand?.industry,
          brandTone: brand?.toneOfVoice,
          objective: goal,
          platform,
          format: "Display",
          adFormat: selectedRatio,
          visualStyle: selectedStyle,
          productDescription: creativesPrompt.trim() || brand?.productDescription,
          valueProp: creativesPrompt.trim() || undefined,
          variations: creativesCount,
          generateImages: true,
        }),
      })
      const json = await readJson(res)
      if (!res.ok || !json?.success) throw new Error(json?.error || "Couldn't generate creatives.")
      setGeneratedCreatives(json.variations || [])
      setGeneratedImageUrls(json.imageUrls || [])
      if (json.imageError) setCreativesError(json.imageError)
    } catch (err: any) {
      setCreativesError(err?.message || "Something went wrong generating creatives.")
    } finally {
      setGeneratingCreatives(false)
    }
  }

  const handleLaunch = async () => {
    if (!campaignPlanId || launching) return
    setLaunching(true)
    setLaunchError("")
    try {
      const res = await fetch(`/api/ai/campaign-plan/${campaignPlanId}/launch`, { method: "POST" })
      const json = await readJson(res)
      if (!res.ok || !json?.ok) throw new Error(json?.error?.message || json?.error || "Launch failed. Please review the plan and try again.")
      setLaunched({ externalCampaignId: json?.data?.externalCampaignId })
      window.dispatchEvent(new Event("growzzy:onboarding-progress-updated"))
      setTimeout(() => router.push("/dashboard/ads"), 1400)
    } catch (err: any) {
      setLaunchError(err?.message || "Launch failed.")
    } finally {
      setLaunching(false)
    }
  }

  const platformName = platform === "META" ? "Meta Ads" : "Google Ads"
  const platformConnected = platform === "META" ? metaConnected : googleConnected
  const launchChecklist = [
    { label: "Campaign strategy built", done: built },
    { label: "AI creatives generated (optional)", done: generatedCreatives.length > 0, optional: true },
    { label: `${platformName} connected`, done: platformConnected },
  ]
  const canLaunch = built && platformConnected && !!campaignPlanId

  if (editorPlanId) return <CampaignBuilderPage />

  return (
    <Shell title="">
      <div className="flex h-full">
        <div
          className="w-[200px] shrink-0 border-r border-[#DDE1E7] flex flex-col overflow-y-auto"
          style={{ background: 'linear-gradient(180deg, #f8f9fb 0%, #f3f5f7 100%)' }}
        >
          <div className="px-3 pt-4 pb-2">
            <div className="flex items-center justify-between mb-2">
              <span className="text-[10.5px] font-semibold text-[#9CA3AF] uppercase tracking-[0.08em]">Recent</span>
            </div>
            <p className="text-[11px] text-[#9CA3AF] italic px-2 py-1">
              <a href="/dashboard/prompts" className="hover:text-[#1F57F5] transition-colors underline">View saved briefs →</a>
            </p>
          </div>
        </div>

        <div className="flex-1 flex flex-col items-center justify-center px-8 py-10 min-h-0 overflow-y-auto">
          <div className="w-full max-w-[680px] text-center mb-8">
            <h1 className="text-[30px] text-[#111827] leading-tight mb-2 tracking-tight text-balance" style={{ fontWeight: 500 }}>
              {built ? "Campaign plan ready." : "Run ad campaigns in minutes."}
            </h1>
            <p className="text-[14px] text-[#6B7280] leading-relaxed">
              {built
                ? `"${campaignName}" is ready. Generate creatives and launch when ready, or open the full editor for fine control.`
                : "Tell Growzzy what you want to promote. AI builds the strategy, targeting and ads for you."}
            </p>
          </div>

          <div className="flex items-center gap-1.5 mb-6">
            {TABS.map(({ id, label, icon: Icon }) => (
              <button
                key={id}
                onClick={() => setActiveTab(id)}
                className={cn(
                  "flex items-center gap-1.5 h-8 px-3.5 rounded-full text-[12.5px] transition-colors",
                  activeTab === id ? "bg-[#EAF0FE] text-[#1F57F5] font-semibold" : "text-[#6B7280] hover:text-[#374151] sku-btn"
                )}
                style={activeTab === id ? { boxShadow: '0 1px 0 rgba(255,255,255,0.8) inset, 0 1px 3px rgba(31,87,245,0.15), 0 0 0 1px rgba(31,87,245,0.2)' } : {}}
              >
                <Icon size={12} className="shrink-0" />
                {label}
              </button>
            ))}
          </div>

          {/* Campaign tab */}
          {activeTab === "campaign" && (
            <div className="w-full max-w-[680px]">
              <div className="bg-white rounded-[16px] overflow-hidden" style={{ border: '2px solid #1F57F5', boxShadow: '0 0 0 4px rgba(31,87,245,0.08), 0 4px 20px rgba(0,0,0,0.08)' }}>
                <textarea
                  ref={textareaRef}
                  value={prompt}
                  onChange={(e) => {
                    setPrompt(e.target.value)
                    setEnhancedBrief(null)
                    setClarifications([])
                  }}
                  placeholder="I want to sell artificial jewelry on my Shopify store to women aged 30-50 in India's Tier 1 cities..."
                  rows={6}
                  className="w-full px-4 pt-4 pb-2 text-[13.5px] text-[#111827] placeholder-[#9CA3AF] bg-transparent resize-none outline-none leading-relaxed"
                />
                <div className="flex justify-end px-4 pb-2">
                  <button onClick={handleEnhance} disabled={!prompt.trim() || enhancing} className="flex items-center gap-1 text-[12px] font-semibold text-[#1F57F5] hover:text-[#1849d6] disabled:opacity-40 transition-colors">
                    {enhancing ? (<><RefreshCw size={11} className="animate-spin" />Enhancing…</>) : (<><Wand2 size={11} />AI Enhance</>)}
                  </button>
                </div>
                <div className="flex items-center justify-between px-3 pb-3 pt-1 border-t border-[#E9EBEF]">
                  <div className="flex items-center gap-1 flex-wrap">
                    {CHIPS.map((chip) => {
                      const active = detected.has(chip.id)
                      return (
                        <span key={chip.id} className={cn("flex items-center gap-1 text-[11px] px-2 py-0.5 rounded-full transition-colors", active ? "text-[#2E9E5B] font-semibold" : "text-[#9CA3AF] font-medium")}>
                          {active ? <CheckCircle2 size={11} className="text-[#2E9E5B]" /> : <Circle size={11} className="text-[#D1D5DB]" />}
                          {chip.label}
                        </span>
                      )
                    })}
                  </div>
                </div>
              </div>

              {enhanceError && <p className="text-[12px] text-[#D3564C] mt-2">{enhanceError}</p>}

              {enhancedBrief && (
                <div className="sku-card mt-4 p-4">
                  <div className="flex items-start justify-between gap-3">
                    <div>
                      <p className="text-[12px] font-semibold text-[#111827]">What Growzzy understood</p>
                      <p className="text-[11px] text-[#6B7280] mt-0.5">Offer: {enhancedBrief.productOrOffer} · Audience: {enhancedBrief.targetCustomer}</p>
                    </div>
                    <span className="text-[10px] font-semibold text-[#2E9E5B] bg-[#E6F4EC] px-2 py-1 rounded-full">AI enhanced</span>
                  </div>
                  {enhancedBrief.missingQuestions.length > 0 && (
                    <div className="mt-3 space-y-2">
                      <p className="text-[11px] font-semibold text-[#374151]">A few details would make the plan stronger</p>
                      {enhancedBrief.missingQuestions.map((question, index) => (
                        <label key={question} className="block">
                          <span className="block text-[11px] text-[#6B7280] mb-1">{question}</span>
                          <input
                            value={clarifications[index] || ""}
                            onChange={(event) => setClarifications((current) => {
                              const next = [...current]
                              next[index] = event.target.value
                              return next
                            })}
                            placeholder="Optional answer"
                            className="sku-input w-full h-9 text-[12px]"
                          />
                        </label>
                      ))}
                    </div>
                  )}
                </div>
              )}

              <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mt-4">
                {TEMPLATES.map((template) => (
                  <button
                    key={template.label}
                    type="button"
                    onClick={() => {
                      setPrompt(template.prompt)
                      setGoal(template.goal)
                      setBudget(template.budget)
                    }}
                    className="sku-btn h-9 rounded-[8px] text-[12px] font-semibold text-[#374151]"
                  >
                    {template.label}
                  </button>
                ))}
              </div>

              {/* Real budget/location/goal — required to build a plan */}
              <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-3 mt-4">
                <div>
                  <label className="block text-[11.5px] font-semibold text-[#374151] mb-1">Daily budget ($)</label>
                  <input type="number" min={1} value={budget} onChange={(e) => setBudget(Number(e.target.value))} className="w-full h-9 px-3 text-[13px] text-[#111827] outline-none rounded-[8px] sku-input" />
                </div>
                <div>
                  <label className="block text-[11.5px] font-semibold text-[#374151] mb-1">Target location</label>
                  <input type="text" placeholder={effectiveLocation || "e.g. United Kingdom"} value={location} onChange={(e) => setLocation(e.target.value)} className="w-full h-9 px-3 text-[13px] text-[#111827] placeholder-[#9CA3AF] outline-none rounded-[8px] sku-input" />
                </div>
                <div>
                  <label className="block text-[11.5px] font-semibold text-[#374151] mb-1">Goal</label>
                  <div className="relative">
                    <select value={goal} onChange={(e) => setGoal(e.target.value)} className="w-full h-9 pl-3 pr-8 text-[13px] text-[#111827] outline-none appearance-none rounded-[8px] sku-input">
                      {GOALS.map((g) => <option key={g.value} value={g.value}>{g.label}</option>)}
                    </select>
                    <ChevronDown size={13} className="absolute right-3 top-1/2 -translate-y-1/2 text-[#9CA3AF] pointer-events-none" />
                  </div>
                </div>
                <div>
                  <label className="block text-[11.5px] font-semibold text-[#374151] mb-1">Platform</label>
                  <div className="relative">
                    <select
                      value={platform}
                      onChange={(e) => {
                        setPlatform(e.target.value)
                        setBuilt(false)
                        setCampaignPlanId(null)
                        setLaunched(null)
                      }}
                      className="w-full h-9 pl-3 pr-8 text-[13px] text-[#111827] outline-none appearance-none rounded-[8px] sku-input"
                    >
                      {PLATFORMS.map((item) => (
                        <option key={item.value} value={item.value} disabled={item.value === "META" && !META_ENABLED}>
                          {item.label}{item.value === "META" && !META_ENABLED ? " (sandbox pending)" : ""}
                        </option>
                      ))}
                    </select>
                    <ChevronDown size={13} className="absolute right-3 top-1/2 -translate-y-1/2 text-[#9CA3AF] pointer-events-none" />
                  </div>
                </div>
              </div>

              {platform === "META" && (
                <div className="mt-4">
                  <label className="block text-[11.5px] font-semibold text-[#374151] mb-1">Meta objective</label>
                  <div className="relative">
                    <select value={metaObjective} onChange={(e) => setMetaObjective(e.target.value)} className="w-full h-9 pl-3 pr-8 text-[13px] text-[#111827] outline-none appearance-none rounded-[8px] sku-input">
                      <option value="">Select objective</option>
                      {META_OBJECTIVES.map((objective) => <option key={objective.value} value={objective.value}>{objective.label}</option>)}
                    </select>
                    <ChevronDown size={13} className="absolute right-3 top-1/2 -translate-y-1/2 text-[#9CA3AF] pointer-events-none" />
                  </div>
                </div>
              )}

              <div className="mt-4">
                <label className="block text-[11.5px] font-semibold text-[#374151] mb-1">Landing page URL</label>
                <input
                  type="url"
                  placeholder="https://yourwebsite.com/offer"
                  value={landingPageUrl}
                  onChange={(event) => setLandingPageUrl(event.target.value)}
                  className="w-full h-9 px-3 text-[13px] text-[#111827] placeholder-[#9CA3AF] outline-none rounded-[8px] sku-input"
                />
                <p className="text-[10.5px] text-[#9CA3AF] mt-1">You can build without it, but a real URL is required before launch.</p>
              </div>

              <div className="flex justify-end mt-3">
                <button
                  onClick={handleBuild}
                  disabled={!canBuildPlan}
                  className={cn(
                    "flex items-center gap-1.5 h-9 px-5 rounded-full text-[13px] font-semibold transition-colors",
                    canBuildPlan ? "text-white sku-btn-primary" : "bg-[#E9EBEF] text-[#9CA3AF] cursor-not-allowed"
                  )}
                >
                  {building ? (<><Loader2 size={13} className="animate-spin" />Building…</>) : built ? (<><Check size={13} />Plan ready — rebuild</>) : (<><Sparkles size={13} />Build plan<ArrowRight size={13} /></>)}
                </button>
              </div>

              {buildError && (
                <div className="mt-4 p-3 rounded-[12px] border border-[#D3564C]/30 bg-[#FBE7E5]">
                  <p className="text-[12.5px] font-medium text-[#D3564C]">{buildError}</p>
                </div>
              )}
              {built && (
                <div className="mt-4 p-4 rounded-[12px] border border-[#2E9E5B]/30 bg-[#E6F4EC]">
                  <p className="text-[13px] font-semibold text-[#2E9E5B] mb-1 flex items-center gap-1.5"><Check size={14} /> Campaign plan generated</p>
                  <p className="text-[12px] text-[#374151]">
                    "{campaignName}" was created and saved as a draft. Generate creatives, launch it here, or open the full editor to fine-tune keywords and ad copy.
                  </p>
                  <div className="flex items-center gap-4 mt-3">
                    <button onClick={() => setActiveTab("creatives")} className="flex items-center gap-1.5 text-[12.5px] font-semibold text-[#1F57F5] hover:text-[#1849d6] transition-colors">
                      Generate AI creatives <ArrowRight size={12} />
                    </button>
                    <a href={`/dashboard/campaigns/builder?id=${campaignPlanId}`} className="flex items-center gap-1.5 text-[12.5px] font-semibold text-[#374151] hover:text-[#111827] transition-colors">
                      Open full editor <ExternalLink size={12} />
                    </a>
                  </div>
                </div>
              )}
            </div>
          )}

          {/* Boolean search tab */}
          {activeTab === "boolean" && (
            <div className="w-full max-w-[680px]">
              <div className="sku-card p-5">
                <p className="text-[14px] font-semibold text-[#111827] mb-1">Boolean Audience Search</p>
                <p className="text-[12.5px] text-[#6B7280] mb-4">
                  Describe your audience with AND/OR/NOT operators. AI translates it into real Google Search keywords — Google Ads has no native boolean audience targeting, so this maps your intent to search terms real people would type.
                </p>
                <div className="space-y-3">
                  <textarea
                    value={booleanQuery}
                    onChange={(e) => setBooleanQuery(e.target.value)}
                    rows={4}
                    placeholder={`e.g. (women OR female) AND (fashion OR jewelry) AND (India OR Mumbai) AND age:30-50`}
                    className="w-full px-3 py-2.5 text-[13px] text-[#111827] placeholder-[#9CA3AF] resize-none outline-none leading-relaxed rounded-[8px] sku-input"
                  />
                  <div className="flex gap-2">
                    {["AND", "OR", "NOT", "( )", "age:", "location:"].map((op) => (
                      <button key={op} onClick={() => setBooleanQuery((q) => q + (q ? " " : "") + op)} className="h-7 px-2.5 text-[11.5px] font-semibold text-[#374151] rounded-[6px] sku-btn">
                        {op}
                      </button>
                    ))}
                  </div>
                  <button
                    onClick={handleBooleanSearch}
                    disabled={!booleanQuery.trim() || booleanLoading}
                    className={cn("flex items-center gap-1.5 h-9 px-5 rounded-[8px] text-[13px] font-semibold transition-colors", booleanQuery.trim() && !booleanLoading ? "text-white sku-btn-primary" : "bg-[#E9EBEF] text-[#9CA3AF] cursor-not-allowed")}
                  >
                    {booleanLoading ? (<><Loader2 size={13} className="animate-spin" />Translating…</>) : (<><Search size={13} />Search audience</>)}
                  </button>
                  {booleanError && <p className="text-[12px] text-[#D3564C]">{booleanError}</p>}
                </div>
              </div>

              {booleanResult && (
                <div className="sku-card p-5 mt-4">
                  <p className="text-[12.5px] text-[#374151] mb-3">{booleanResult.interpretation}</p>
                  <p className="text-[11.5px] font-semibold text-[#9CA3AF] uppercase tracking-wider mb-2">Suggested keywords</p>
                  <div className="flex flex-wrap gap-1.5 mb-3">
                    {booleanResult.keywords.map((k, i) => (
                      <span key={i} title={k.rationale} className="inline-flex items-center h-6 px-2 rounded-full text-[11px] font-medium bg-[#EAF0FE] text-[#1F57F5]" >
                        {k.text} <span className="ml-1 text-[9.5px] text-[#1F57F5]/60">{k.matchType}</span>
                      </span>
                    ))}
                  </div>
                  {booleanResult.negativeKeywords.length > 0 && (
                    <>
                      <p className="text-[11.5px] font-semibold text-[#9CA3AF] uppercase tracking-wider mb-2">Suggested negatives</p>
                      <div className="flex flex-wrap gap-1.5">
                        {booleanResult.negativeKeywords.map((k, i) => (
                          <span key={i} className="inline-flex items-center h-6 px-2 rounded-full text-[11px] font-medium bg-[#FBE7E5] text-[#D3564C]">−{k}</span>
                        ))}
                      </div>
                    </>
                  )}
                  <p className="text-[11px] text-[#9CA3AF] mt-3">Use these in the Campaign tab's brief, or paste them into the full editor's keyword list.</p>
                </div>
              )}
            </div>
          )}

          {/* AI Creatives tab */}
          {activeTab === "creatives" && (
            <div className="w-full max-w-[720px]">
              <div className="sku-card p-5 mb-5">
                <div className="flex items-center gap-2 mb-3">
                  <ImageIcon size={15} className="text-[#1F57F5]" />
                  <p className="text-[14px] font-semibold text-[#111827]">AI Ad Creatives</p>
                </div>
                <div className="space-y-3.5">
                  <div>
                    <label className="block text-[12px] font-semibold text-[#374151] mb-1.5">Describe the ad visual</label>
                    <textarea
                      value={creativesPrompt}
                      onChange={(e) => setCreativesPrompt(e.target.value)}
                      rows={3}
                      placeholder="A luxury jewelry ad showing a woman at a festive wedding event, warm gold tones, elegant and premium feel..."
                      className="w-full px-3 py-2.5 text-[13px] text-[#111827] placeholder-[#9CA3AF] resize-none outline-none leading-relaxed rounded-[8px] sku-input"
                    />
                  </div>
                  <div className="grid grid-cols-3 gap-3">
                    <div>
                      <label className="block text-[12px] font-semibold text-[#374151] mb-1.5">Ad Style</label>
                      <div className="flex flex-wrap gap-1.5">
                        {AD_STYLES.map((s) => (
                          <button key={s} onClick={() => setSelectedStyle(s)} className={cn("h-7 px-2.5 text-[11.5px] rounded-[6px] transition-colors", selectedStyle === s ? "bg-[#EAF0FE] text-[#1F57F5] font-semibold" : "text-[#4B5563] font-medium sku-btn")}>
                            {s}
                          </button>
                        ))}
                      </div>
                    </div>
                    <div>
                      <label className="block text-[12px] font-semibold text-[#374151] mb-1.5">Aspect Ratio</label>
                      <div className="flex gap-1.5">
                        {ASPECT_RATIOS.map(({ label, desc }) => (
                          <button key={label} onClick={() => setSelectedRatio(label)} className={cn("flex flex-col items-center px-2 py-1.5 rounded-[6px] transition-colors", selectedRatio === label ? "bg-[#EAF0FE] text-[#1F57F5]" : "text-[#4B5563] sku-btn")}>
                            <span className="text-[11.5px] font-bold leading-none">{label}</span>
                            <span className="text-[9.5px] text-[#9CA3AF] leading-none mt-0.5">{desc}</span>
                          </button>
                        ))}
                      </div>
                    </div>
                    <div>
                      <label className="block text-[12px] font-semibold text-[#374151] mb-1.5">No. of variants</label>
                      <div className="relative">
                        <select value={creativesCount} onChange={(e) => setCreativesCount(Number(e.target.value))} className="w-full h-9 pl-3 pr-8 text-[12.5px] text-[#111827] outline-none appearance-none rounded-[8px] sku-input">
                          {[1, 2, 3, 4].map((n) => (<option key={n} value={n}>{n} variant{n > 1 ? "s" : ""}</option>))}
                        </select>
                        <ChevronDown size={13} className="absolute right-3 top-1/2 -translate-y-1/2 text-[#9CA3AF] pointer-events-none" />
                      </div>
                    </div>
                  </div>
                  <button
                    onClick={handleGenerateCreatives}
                    disabled={generatingCreatives || !creativesPrompt.trim()}
                    className={cn("flex items-center justify-center gap-2 h-10 w-full rounded-[10px] text-[13.5px] font-semibold transition-colors", !generatingCreatives && creativesPrompt.trim() ? "text-white sku-btn-primary" : "bg-[#E9EBEF] text-[#9CA3AF] cursor-not-allowed")}
                  >
                    {generatingCreatives ? (<><Loader2 size={16} className="animate-spin" />Generating creatives…</>) : (<><Sparkles size={14} />Generate {creativesCount} AI creative{creativesCount > 1 ? "s" : ""}</>)}
                  </button>
                  {creativesError && <p className="text-[12px] text-[#D3564C]">{creativesError}</p>}
                </div>
              </div>

              {generatedCreatives.length > 0 && (
                <div>
                  <div className="flex items-center justify-between mb-3">
                    <p className="text-[13.5px] font-semibold text-[#111827]">{generatedCreatives.length} creative{generatedCreatives.length > 1 ? "s" : ""} generated</p>
                    <button onClick={handleGenerateCreatives} className="flex items-center gap-1 text-[12px] font-semibold text-[#1F57F5] hover:text-[#1849d6] transition-colors">
                      <RefreshCw size={12} /> Regenerate
                    </button>
                  </div>
                  <div className={cn("grid gap-4", generatedCreatives.length === 1 ? "grid-cols-1 max-w-[280px]" : generatedCreatives.length === 2 ? "grid-cols-2" : "grid-cols-2 lg:grid-cols-4")}>
                    {generatedCreatives.map((c, i) => (
                      <CreativeCard key={i} variation={c} imageUrl={generatedImageUrls[i] || null} ratio={selectedRatio} />
                    ))}
                  </div>
                  <div className="mt-4">
                    <button onClick={() => setActiveTab("launch")} className="flex items-center gap-1.5 h-9 px-5 text-white text-[13px] font-semibold rounded-[8px] sku-btn-primary">
                      <Rocket size={13} /> Continue to Launch <ArrowRight size={13} />
                    </button>
                  </div>
                </div>
              )}
            </div>
          )}

          {/* Launch Ads tab */}
          {activeTab === "launch" && (
            <div className="w-full max-w-[680px]">
              <div className="sku-card p-6">
                <div className="flex items-center gap-2 mb-4">
                  <Rocket size={16} className="text-[#1F57F5]" />
                  <p className="text-[14px] font-semibold text-[#111827]">Launch to {platformName}</p>
                </div>
                {!campaignPlanId && (
                  <div className="p-3 rounded-[10px] bg-[#FBF0DA] text-[#B8892B] text-[12.5px] font-medium mb-4">
                    Build a campaign plan in the Campaign tab first.
                  </div>
                )}
                <div className="space-y-3">
                  {launchChecklist.map(({ label, done, optional }) => (
                    <div key={label} className="flex items-center gap-3 p-3 rounded-[10px]" style={{ background: done === true ? '#E6F4EC' : 'linear-gradient(145deg, #f8f9fb 0%, #f0f2f5 100%)' }}>
                      <div className="w-7 h-7 rounded-full flex items-center justify-center shrink-0" style={done === true ? { background: 'linear-gradient(135deg, #34c471 0%, #2E9E5B 100%)', color: 'white' } : { background: 'linear-gradient(145deg, #e8eaed 0%, #f4f5f7 100%)', color: '#9CA3AF' }}>
                        {done ? <Check size={13} /> : <Circle size={12} />}
                      </div>
                      <span className={cn("text-[13px]", done === true ? "font-semibold text-[#2E9E5B]" : "font-medium text-[#4B5563]")}>{done === null ? "Checking connection..." : label}</span>
                      {done === false && !optional && label === `${platformName} connected` && (
                        <a href={platform === "META" ? "/api/integrations/meta/connect" : "/api/integrations/google/connect"} className="ml-auto text-[11.5px] font-semibold text-[#1F57F5] hover:text-[#1849d6] transition-colors">Connect →</a>
                      )}
                    </div>
                  ))}
                </div>
                {launchError && (
                  <div className="mt-4 p-3 rounded-[10px] border border-[#D3564C]/30 bg-[#FBE7E5]">
                    <p className="text-[12.5px] font-medium text-[#D3564C]">{launchError}</p>
                  </div>
                )}
                {launched ? (
                  <div className="mt-5 p-4 rounded-[10px] border border-[#2E9E5B]/30 bg-[#E6F4EC] text-center">
                    <p className="text-[13px] font-semibold text-[#2E9E5B] flex items-center justify-center gap-1.5"><Check size={14} /> Launched to {platformName} (paused)</p>
                    <p className="text-[11.5px] text-[#374151] mt-1">Redirecting to Ads Manager…</p>
                  </div>
                ) : (
                  <button
                    onClick={handleLaunch}
                    disabled={!canLaunch || launching}
                    className={cn("mt-5 flex items-center justify-center gap-2 h-11 w-full rounded-[10px] text-[14px] font-semibold transition-colors", canLaunch && !launching ? "text-white sku-btn-primary" : "bg-[#E9EBEF] text-[#9CA3AF] cursor-not-allowed")}
                  >
                    {launching ? (<><Loader2 size={16} className="animate-spin" />Launching…</>) : (<><Rocket size={15} />Launch {platformName} Campaign</>)}
                  </button>
                )}
              </div>
            </div>
          )}
        </div>
      </div>
    </Shell>
  )
}
